#pragma once

#include <cstdint>
#include <map>
#include <string>

namespace Abyss {
    namespace GUI {
        namespace InputDefinitions {
            enum class ACTION : std::uint8_t;
            enum class KEY : std::uint16_t;
            enum class MOUSE_BUTTON : std::uint8_t;
            enum class MOD : std::uint8_t;
            extern std::map<KEY, std::string> keyToString;
        }
    }
}

enum class Abyss::GUI::InputDefinitions::ACTION : std::uint8_t {
    ACTION_RELEASE = 0,
    ACTION_PRESS   = 1,
    ACTION_REPEAT  = 2
};

enum class Abyss::GUI::InputDefinitions::KEY : std::uint16_t {
    KEY_UNKNOWN       = 1,
    KEY_SPACE         = 32,
    KEY_APOSTROPHE    = 39,
    KEY_COMMA         = 44,
    KEY_MINUS         = 45,
    KEY_PERIOD        = 46,
    KEY_SLASH         = 47,
    KEY_0             = 48,
    KEY_1             = 49,
    KEY_2             = 50,
    KEY_3             = 51,
    KEY_4             = 52,
    KEY_5             = 53,
    KEY_6             = 54,
    KEY_7             = 55,
    KEY_8             = 56,
    KEY_9             = 57,
    KEY_SEMICOLON     = 59,
    KEY_EQUAL         = 61,
    KEY_A             = 65,
    KEY_B             = 66,
    KEY_C             = 67,
    KEY_D             = 68,
    KEY_E             = 69,
    KEY_F             = 70,
    KEY_G             = 71,
    KEY_H             = 72,
    KEY_I             = 73,
    KEY_J             = 74,
    KEY_K             = 75,
    KEY_L             = 76,
    KEY_M             = 77,
    KEY_N             = 78,
    KEY_O             = 79,
    KEY_P             = 80,
    KEY_Q             = 81,
    KEY_R             = 82,
    KEY_S             = 83,
    KEY_T             = 84,
    KEY_U             = 85,
    KEY_V             = 86,
    KEY_W             = 87,
    KEY_X             = 88,
    KEY_Y             = 89,
    KEY_Z             = 90,
    KEY_LEFT_BRACKET  = 91,
    KEY_BACKSLASH     = 92,
    KEY_RIGHT_BRACKET = 93,
    KEY_GRAVE_ACCENT  = 96,
    KEY_WORLD_1       = 161,
    KEY_WORLD_2       = 162,
    KEY_ESCAPE        = 256,
    KEY_ENTER         = 257,
    KEY_TAB           = 258,
    KEY_BACKSPACE     = 259,
    KEY_INSERT        = 260,
    KEY_DELETE        = 261,
    KEY_RIGHT         = 262,
    KEY_LEFT          = 263,
    KEY_DOWN          = 264,
    KEY_UP            = 265,
    KEY_PAGE_UP       = 266,
    KEY_PAGE_DOWN     = 267,
    KEY_HOME          = 268,
    KEY_END           = 269,
    KEY_CAPS_LOCK     = 280,
    KEY_SCROLL_LOCK   = 281,
    KEY_NUM_LOCK      = 282,
    KEY_PRINT_SCREEN  = 283,
    KEY_PAUSE         = 284,
    KEY_F1            = 290,
    KEY_F2            = 291,
    KEY_F3            = 292,
    KEY_F4            = 293,
    KEY_F5            = 294,
    KEY_F6            = 295,
    KEY_F7            = 296,
    KEY_F8            = 297,
    KEY_F9            = 298,
    KEY_F10           = 299,
    KEY_F11           = 300,
    KEY_F12           = 301,
    KEY_F13           = 302,
    KEY_F14           = 303,
    KEY_F15           = 304,
    KEY_F16           = 305,
    KEY_F17           = 306,
    KEY_F18           = 307,
    KEY_F19           = 308,
    KEY_F20           = 309,
    KEY_F21           = 310,
    KEY_F22           = 311,
    KEY_F23           = 312,
    KEY_F24           = 313,
    KEY_F25           = 314,
    KEY_KP_0          = 320,
    KEY_KP_1          = 321,
    KEY_KP_2          = 322,
    KEY_KP_3          = 323,
    KEY_KP_4          = 324,
    KEY_KP_5          = 325,
    KEY_KP_6          = 326,
    KEY_KP_7          = 327,
    KEY_KP_8          = 328,
    KEY_KP_9          = 329,
    KEY_KP_DECIMAL    = 330,
    KEY_KP_DIVIDE     = 331,
    KEY_KP_MULTIPLY   = 332,
    KEY_KP_SUBTRACT   = 333,
    KEY_KP_ADD        = 334,
    KEY_KP_ENTER      = 335,
    KEY_KP_EQUAL      = 336,
    KEY_LEFT_SHIFT    = 340,
    KEY_LEFT_CONTROL  = 341,
    KEY_LEFT_ALT      = 342,
    KEY_LEFT_SUPER    = 343,
    KEY_RIGHT_SHIFT   = 344,
    KEY_RIGHT_CONTROL = 345,
    KEY_RIGHT_ALT     = 346,
    KEY_RIGHT_SUPER   = 347,
    KEY_MENU          = 348,
    KEY_LAST          = KEY_MENU
};

enum class Abyss::GUI::InputDefinitions::MOUSE_BUTTON : std::uint8_t {
    MOUSE_BUTTON_1      = 0,
    MOUSE_BUTTON_2      = 1,
    MOUSE_BUTTON_3      = 2,
    MOUSE_BUTTON_4      = 3,
    MOUSE_BUTTON_5      = 4,
    MOUSE_BUTTON_6      = 5,
    MOUSE_BUTTON_7      = 6,
    MOUSE_BUTTON_8      = 7,
    MOUSE_BUTTON_LAST   = MOUSE_BUTTON_8,
    MOUSE_BUTTON_LEFT   = MOUSE_BUTTON_1,
    MOUSE_BUTTON_RIGHT  = MOUSE_BUTTON_2,
    MOUSE_BUTTON_MIDDLE = MOUSE_BUTTON_3
};

enum class Abyss::GUI::InputDefinitions::MOD : std::uint8_t {
    MODS_SHIFT     = 0x0001,
    MODS_CONTROL   = 0x0002,
    MODS_ALT       = 0x0004,
    MODS_SUPER     = 0x0008,
    MODS_CAPS_LOCK = 0x0010,
    MODS_NUM_LOCK  = 0x0020
};

std::map<Abyss::GUI::InputDefinitions::KEY, std::string> Abyss::GUI::InputDefinitions::keyToString{
{Abyss::GUI::InputDefinitions::KEY::KEY_UNKNOWN, "UNKNOWN"},
{Abyss::GUI::InputDefinitions::KEY::KEY_SPACE, "SPACE"},
{Abyss::GUI::InputDefinitions::KEY::KEY_APOSTROPHE, "APOSTROPHE"},
{Abyss::GUI::InputDefinitions::KEY::KEY_COMMA, "COMMA"},
{Abyss::GUI::InputDefinitions::KEY::KEY_MINUS, "MINUS"},
{Abyss::GUI::InputDefinitions::KEY::KEY_PERIOD, "PERIOD"},
{Abyss::GUI::InputDefinitions::KEY::KEY_SLASH, "SLASH"},
{Abyss::GUI::InputDefinitions::KEY::KEY_0, "0"},
{Abyss::GUI::InputDefinitions::KEY::KEY_1, "1"},
{Abyss::GUI::InputDefinitions::KEY::KEY_2, "2"},
{Abyss::GUI::InputDefinitions::KEY::KEY_3, "3"},
{Abyss::GUI::InputDefinitions::KEY::KEY_4, "4"},
{Abyss::GUI::InputDefinitions::KEY::KEY_5, "5"},
{Abyss::GUI::InputDefinitions::KEY::KEY_6, "6"},
{Abyss::GUI::InputDefinitions::KEY::KEY_7, "7"},
{Abyss::GUI::InputDefinitions::KEY::KEY_8, "8"},
{Abyss::GUI::InputDefinitions::KEY::KEY_9, "9"},
{Abyss::GUI::InputDefinitions::KEY::KEY_SEMICOLON, "SEMICOLON"},
{Abyss::GUI::InputDefinitions::KEY::KEY_EQUAL, "EQUAL"},
{Abyss::GUI::InputDefinitions::KEY::KEY_A, "A"},
{Abyss::GUI::InputDefinitions::KEY::KEY_B, "B"},
{Abyss::GUI::InputDefinitions::KEY::KEY_C, "C"},
{Abyss::GUI::InputDefinitions::KEY::KEY_D, "D"},
{Abyss::GUI::InputDefinitions::KEY::KEY_E, "E"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F, "F"},
{Abyss::GUI::InputDefinitions::KEY::KEY_G, "G"},
{Abyss::GUI::InputDefinitions::KEY::KEY_H, "H"},
{Abyss::GUI::InputDefinitions::KEY::KEY_I, "I"},
{Abyss::GUI::InputDefinitions::KEY::KEY_J, "J"},
{Abyss::GUI::InputDefinitions::KEY::KEY_K, "K"},
{Abyss::GUI::InputDefinitions::KEY::KEY_L, "L"},
{Abyss::GUI::InputDefinitions::KEY::KEY_M, "M"},
{Abyss::GUI::InputDefinitions::KEY::KEY_N, "N"},
{Abyss::GUI::InputDefinitions::KEY::KEY_O, "O"},
{Abyss::GUI::InputDefinitions::KEY::KEY_P, "P"},
{Abyss::GUI::InputDefinitions::KEY::KEY_Q, "Q"},
{Abyss::GUI::InputDefinitions::KEY::KEY_R, "R"},
{Abyss::GUI::InputDefinitions::KEY::KEY_S, "S"},
{Abyss::GUI::InputDefinitions::KEY::KEY_T, "T"},
{Abyss::GUI::InputDefinitions::KEY::KEY_U, "U"},
{Abyss::GUI::InputDefinitions::KEY::KEY_V, "V"},
{Abyss::GUI::InputDefinitions::KEY::KEY_W, "W"},
{Abyss::GUI::InputDefinitions::KEY::KEY_X, "X"},
{Abyss::GUI::InputDefinitions::KEY::KEY_Y, "Y"},
{Abyss::GUI::InputDefinitions::KEY::KEY_Z, "Z"},
{Abyss::GUI::InputDefinitions::KEY::KEY_LEFT_BRACKET, "LEFT_BRACKET"},
{Abyss::GUI::InputDefinitions::KEY::KEY_BACKSLASH, "BACKSLASH"},
{Abyss::GUI::InputDefinitions::KEY::KEY_RIGHT_BRACKET, "RIGHT_BRACKET"},
{Abyss::GUI::InputDefinitions::KEY::KEY_GRAVE_ACCENT, "GRAVE_ACCENT"},
{Abyss::GUI::InputDefinitions::KEY::KEY_WORLD_1, "WORLD_1"},
{Abyss::GUI::InputDefinitions::KEY::KEY_WORLD_2, "WORLD_2"},
{Abyss::GUI::InputDefinitions::KEY::KEY_ESCAPE, "ESCAPE"},
{Abyss::GUI::InputDefinitions::KEY::KEY_ENTER, "ENTER"},
{Abyss::GUI::InputDefinitions::KEY::KEY_TAB, "TAB"},
{Abyss::GUI::InputDefinitions::KEY::KEY_BACKSPACE, "BACKSPACE"},
{Abyss::GUI::InputDefinitions::KEY::KEY_INSERT, "INSERT"},
{Abyss::GUI::InputDefinitions::KEY::KEY_DELETE, "DELETE"},
{Abyss::GUI::InputDefinitions::KEY::KEY_RIGHT, "RIGHT"},
{Abyss::GUI::InputDefinitions::KEY::KEY_LEFT, "LEFT"},
{Abyss::GUI::InputDefinitions::KEY::KEY_DOWN, "DOWN"},
{Abyss::GUI::InputDefinitions::KEY::KEY_UP, "UP"},
{Abyss::GUI::InputDefinitions::KEY::KEY_PAGE_UP, "PAGE_UP"},
{Abyss::GUI::InputDefinitions::KEY::KEY_PAGE_DOWN, "PAGE_DOWN"},
{Abyss::GUI::InputDefinitions::KEY::KEY_HOME, "HOME"},
{Abyss::GUI::InputDefinitions::KEY::KEY_END, "END"},
{Abyss::GUI::InputDefinitions::KEY::KEY_CAPS_LOCK, "CAPS_LOCK"},
{Abyss::GUI::InputDefinitions::KEY::KEY_SCROLL_LOCK, "SCROLL_LOCK"},
{Abyss::GUI::InputDefinitions::KEY::KEY_NUM_LOCK, "NUM_LOCK"},
{Abyss::GUI::InputDefinitions::KEY::KEY_PRINT_SCREEN, "PRINT_SCREEN"},
{Abyss::GUI::InputDefinitions::KEY::KEY_PAUSE, "PAUSE"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F1, "F1"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F2, "F2"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F3, "F3"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F4, "F4"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F5, "F5"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F6, "F6"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F7, "F7"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F8, "F8"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F9, "F9"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F10, "F10"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F11, "F11"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F12, "F12"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F13, "F13"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F14, "F14"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F15, "F15"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F16, "F16"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F17, "F17"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F18, "F18"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F19, "F19"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F20, "F20"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F21, "F21"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F22, "F22"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F23, "F23"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F24, "F24"},
{Abyss::GUI::InputDefinitions::KEY::KEY_F25, "F25"},
{Abyss::GUI::InputDefinitions::KEY::KEY_KP_0, "KP_0"},
{Abyss::GUI::InputDefinitions::KEY::KEY_KP_1, "KP_1"},
{Abyss::GUI::InputDefinitions::KEY::KEY_KP_2, "KP_2"},
{Abyss::GUI::InputDefinitions::KEY::KEY_KP_3, "KP_3"},
{Abyss::GUI::InputDefinitions::KEY::KEY_KP_4, "KP_4"},
{Abyss::GUI::InputDefinitions::KEY::KEY_KP_5, "KP_5"},
{Abyss::GUI::InputDefinitions::KEY::KEY_KP_6, "KP_6"},
{Abyss::GUI::InputDefinitions::KEY::KEY_KP_7, "KP_7"},
{Abyss::GUI::InputDefinitions::KEY::KEY_KP_8, "KP_8"},
{Abyss::GUI::InputDefinitions::KEY::KEY_KP_9, "KP_9"},
{Abyss::GUI::InputDefinitions::KEY::KEY_KP_DECIMAL, "KP_DECIMAL"},
{Abyss::GUI::InputDefinitions::KEY::KEY_KP_DIVIDE, "KP_DIVIDE"},
{Abyss::GUI::InputDefinitions::KEY::KEY_KP_MULTIPLY, "KP_MULTIPLY"},
{Abyss::GUI::InputDefinitions::KEY::KEY_KP_SUBTRACT, "KP_SUBTRACT"},
{Abyss::GUI::InputDefinitions::KEY::KEY_KP_ADD, "KP_ADD"},
{Abyss::GUI::InputDefinitions::KEY::KEY_KP_ENTER, "KP_ENTER"},
{Abyss::GUI::InputDefinitions::KEY::KEY_KP_EQUAL, "KP_EQUAL"},
{Abyss::GUI::InputDefinitions::KEY::KEY_LEFT_SHIFT, "LEFT_SHIFT"},
{Abyss::GUI::InputDefinitions::KEY::KEY_LEFT_CONTROL, "LEFT_CONTROL"},
{Abyss::GUI::InputDefinitions::KEY::KEY_LEFT_ALT, "LEFT_ALT"},
{Abyss::GUI::InputDefinitions::KEY::KEY_LEFT_SUPER, "LEFT_SUPER"},
{Abyss::GUI::InputDefinitions::KEY::KEY_RIGHT_SHIFT, "RIGHT_SHIFT"},
{Abyss::GUI::InputDefinitions::KEY::KEY_RIGHT_CONTROL, "RIGHT_CONTROL"},
{Abyss::GUI::InputDefinitions::KEY::KEY_RIGHT_ALT, "RIGHT_ALT"},
{Abyss::GUI::InputDefinitions::KEY::KEY_RIGHT_SUPER, "RIGHT_SUPER"},
{Abyss::GUI::InputDefinitions::KEY::KEY_MENU, "MENU"}};
